- name: UBT configuration
  hosts: ubt
  become_user: root
  vars:
    node_version_major: 18
    node_version_full: 18.12.1
  tasks:
    - name: Upgrade system
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: dist
    - name: Check if filesystem is expandable
      become: true
      ansible.builtin.command: raspi-config nonint get_can_expand
      register: needs_fs_expansion
      changed_when: false
    - name: Expand filesystem
      become: true
      ansible.builtin.command: raspi-config nonint do_expand_rootfs
      when: needs_fs_expansion.stdout == 1
    - name: Install node
      become: true
      ansible.builtin.unarchive:
        src: "https://nodejs.org/download/release/latest-v{{ node_version_major }}.x/node-v{{ node_version_full }}-linux-arm64.tar.gz"
        dest: /opt
        creates: "/opt/node-v{{ node_version_full }}-linux-arm64"
        remote_src: true
    - name: Add node to path
      become: true
      ansible.builtin.copy:
        dest: /etc/profile.d/node_path.sh
        content: "PATH=$PATH:/opt/node-v{{ node_version_full }}-linux-arm64/bin"
        mode: '0755'
    - name: Install hostapd
      become: true
      ansible.builtin.apt:
        name: hostapd
    - name: Clone linux-router
      ansible.builtin.git:
        version: master
        dest: /home/ubt/src/linux-router
        repo: https://github.com/garywill/linux-router.git
    - name: Install UBT AP service
      become: true
      ansible.builtin.copy:
        src: data/ubt_ap.service
        dest: /usr/lib/systemd/system/ubt_ap.service
        mode: '0644'
    - name: Enable UBT AP
      become: true
      ansible.builtin.systemd:
        name: ubt_ap
        enabled: true
        state: started
        daemon-reload: true
    - name: Clone UBT frontend
      ansible.builtin.git:
        version: master
        dest: /home/ubt/src/ubt_frontend
        repo: https://github.com/ratchet34/blindtest-reforged
    - name: Install UBT frontend
      environment:
        PATH: "/opt/node-v{{ node_version_full }}-linux-arm64/bin:{{ ansible_env.PATH }}"
      community.general.npm:
        path: /home/ubt/src/ubt_frontend
    - name: Build production frontend
      environment:
        PATH: "/opt/node-v{{ node_version_full }}-linux-arm64/bin:{{ ansible_env.PATH }}"
      ansible.builtin.command: npm run build
      args:
        creates: /home/ubt/src/ubt_frontend/build
        chdir: /home/ubt/src/ubt_frontend
    - name: Install UBT frontend service
      become: true
      ansible.builtin.copy:
        src: data/ubt_frontend.service
        dest: /usr/lib/systemd/system/ubt_frontend.service
        mode: '0644'
    - name: Enable UBT frontend
      become: true
      ansible.builtin.systemd:
        name: ubt_frontend
        enabled: true
        state: started
        daemon-reload: true
    - name: Clone UBT backend
      ansible.builtin.git:
        version: main
        dest: /home/ubt/src/ubt_backend
        repo: https://github.com/ratchet34/blindtest-reforged-back
    - name: Install UBT backend
      environment:
        PATH: "/opt/node-v{{ node_version_full }}-linux-arm64/bin:{{ ansible_env.PATH }}"
      community.general.npm:
        path: /home/ubt/src/ubt_backend
    - name: Install UBT backend service
      become: true
      ansible.builtin.template:
        src: data/ubt_backend.service
        dest: /usr/lib/systemd/system/ubt_backend.service
        mode: '0644'
    - name: Enable UBT backend
      become: true
      ansible.builtin.systemd:
        name: ubt_backend
        enabled: true
        state: started
        daemon-reload: true
    - name: Reboot
      become: true
      ansible.builtin.reboot:
